### ISSUE TITLE
i think here you need "or " operator rather than and operator

### ISSUE THREAD

**Issue by itsJustAbe** [ChaosAdm/JournalChaosAdm#5]
https://github.com/ChaosAdm/JournalChaosAdm/blob/fe04dd2410ad0d70f80fb119b7dbffb635d31d5c/source.py#L86

**Comment by ChaosAdm** [comment]
It will be "and" because assume someone typed "add", it will still keep asking for inputs as it will satisfy the condition of option.lower()!= "edit" and the others.
